### PR TITLE
Reset encoder weights

### PR DESCRIPTION
**Pull request by b-biswas**
By observing the result on the reconstructions I note the following:

- The model works well for reconstructing isolated galaxies 
- When it comes to deblending, the flux from neighbouring galaxies leak into the predicted central galaxy. 

My hypothesis here is that when I train the entire VAE in the first iteration, I train it with only isolated galaxies (noiseless) as input and the VAE learns to reconstruct everything that is in the image. The Encoder learns to encode all the flux in the image into the latent space. 
Now, when I start the second iteration using the same encoder, I am starting from a minima where the encoder knows to encode all the information in the image into the latent space. Starting from this point might not be a good idea when trying to deblending because, in the 2nd round of training, I want the encoder to reject the flux not coming from the central galaxy.

So this PR does the following:

- [x] reset the encoder to random weights before the second round of training
- [x] make the model for encoder more complex (more parameters) than the decoder because the encoder is in-charge of the deblending.

### CODE REVIEW

**Comment by b-biswas** [comment]
I do not know yet if the results are better but this sounds more logical to me than the previous configuration.

**Review by BastienArcelin — APPROVED** [review]

**Review by BastienArcelin — CHANGES_REQUESTED** [review]
Did you try to make a training that way ? For a multivariate normal layer, the previous dense layer must have a dimension that is equal to the sum of the non-zero elements in this layer, i.e. latent_dim x mu element + all the non-zero elements in the covariance matrix. So to increase the complexity of the network it would be necessary to add a layer if you want, but changing the dimension of the previous dense layer might lead to some problems

**Review by BastienArcelin — APPROVED** [review]

**Comment by BastienArcelin** [comment]
sorry forget my last "approval", there still need to be some changes in the network architecture I think

**Comment by b-biswas** [comment]
> Did you try to make a training that way ? For a multivariate normal layer, the previous dense layer must have a dimension that is equal to the sum of the non-zero elements in this layer, i.e. latent_dim x mu element + all the non-zero elements in the covariance matrix. So to increase the complexity of the network it would be necessary to add a layer if you want, but changing the dimension of the previous dense layer might lead to some problems

The model is currently being currently being trained and the training is working. I did not change the final layer of the encoder so there are no issues!

**Comment by b-biswas** [comment]
> sorry forget my last "approval", there still need to be some changes in the network architecture I think

Yes, definitely. 
But I will come back to the exact architecture later... For now, it's more about the idea of having a  "simple" decoder combined with a complex encoder 
And randomising the weights of encoder

**Comment by BastienArcelin** [comment]
> > Did you try to make a training that way ? For a multivariate normal layer, the previous dense layer must have a dimension that is equal to the sum of the non-zero elements in this layer, i.e. latent_dim x mu element + all the non-zero elements in the covariance matrix. So to increase the complexity of the network it would be necessary to add a layer if you want, but changing the dimension of the previous dense layer might lead to some problems
> 
> The model is currently being trained and the training is working. I did not change the final layer of the encoder so there are no issues!

Ok great but there is something I do not understand: why do you modify the decoder architecture, while it is supposed to be fixed using as the one used on isolated galaxies ?  The modification of the encoder seems fine to me (sorry, I missed some part of the code wile reviewing yesterday). I do not understand why you modified the decoder in this way. I think you could have kept the decoder architecture as it was, and just complexified the encoder one as you did.

**Comment by b-biswas** [comment]
> > > Did you try to make a training that way ? For a multivariate normal layer, the previous dense layer must have a dimension that is equal to the sum of the non-zero elements in this layer, i.e. latent_dim x mu element + all the non-zero elements in the covariance matrix. So to increase the complexity of the network it would be necessary to add a layer if you want, but changing the dimension of the previous dense layer might lead to some problems
> > 
> > 
> > The model is currently being trained and the training is working. I did not change the final layer of the encoder so there are no issues!
> 
> Ok great but there is something I do not understand: why do you modify the decoder architecture, while it is supposed to be fixed using as the one used on isolated galaxies ? The modification of the encoder seems fine to me (sorry, I missed some part of the code wile reviewing yesterday). I do not understand why you modified the decoder in this way. I think you could have kept the decoder architecture as it was, and just complexified the encoder one as you did.

I just increased the complexity of the decoder.
I have made a number of tests looking at reconstructions of isolated galaxies, I think the current configuration is working quite well in reconstructing isolated galaxies.
The reason why I am trying to implement a minimalistic module is because of the flow debender. I plan to use the same architecture in both projects without compromising the results of reconstructions (I will make different architectures later if I fail to do so). 
So yeah more updates to come on the model architecture! 
I will open another PR in a couple of weeks, maybe we can have a broader discussion on this then. For now, I am merging this PR.

**Pull request merged**
